name: CD

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Dokku deploy
        uses: vitalyliber/dokku-github-action@master
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          HOST: 116.203.50.63
          PROJECT: app-name
          APP_CONFIG: ${{ secrets.APP_CONFIG }}
          BRANCH: main